import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import LandingPage from "@/components/LandingPage";
import WorkSummary from "@/components/WorkSummary";
import { useEffect } from "react";
import TitleSlide from "@/components/TitleSlide";
import Inner from "@/components/Inner";
import Slider from "@/components/Slider";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  //initialize locomotive-scroll
  useEffect(() => {
    import("locomotive-scroll").then(locomotiveModule => {
      const scroll = new locomotiveModule.default()
    })
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Inner >
        <>
          <LandingPage />
          <TitleSlide />
          <WorkSummary />
          <Slider />
          <Footer />
        </>
      </Inner>
    </>
  );
}
